//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MST.Net.Models
{
    internal class KodeposMetaData
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Kodepos is required")]
        [RegularExpression(@"^[0-9]{0,5}$", ErrorMessage = "only numbers and length Should be less than 5")]
        public string kode { get; set; }

        [Required(ErrorMessage = "Kelurahan is required")]
        [StringLength(15, ErrorMessage = "Kelurahan length Should be less than 50")]
        public string kelurahan { get; set; }

        [Required(ErrorMessage = "Kelurahan is required")]
        [StringLength(15, ErrorMessage = "Kecamatan length Should be less than 50")]
        public string kecamatan { get; set; }
        public bool type_kab { get; set; }

        [Required(ErrorMessage = "Kelurahan is required")]
        [StringLength(15, ErrorMessage = "Kabupaten length Should be less than 50")]
        public string kabupaten { get; set; }

        [Required(ErrorMessage = "Kelurahan is required")]
        [StringLength(15, ErrorMessage = "Provinsi length Should be less than 50")]
        public string provinsi { get; set; }
    }
}